drop table if exists is_prepared;
drop table if exists preparation;
drop table if exists referral;
drop table if exists order_item;
drop table if exists plain_order;
drop table if exists customer;
drop table if exists article;
drop table if exists category;
drop table if exists delivery_location;
